# Configuration file for the new server\cluster setup in automatic mode.
---
server: 
  ip: "77.223.102.123"
  oldPort: 22
  newPort: 420

users: # list of users to be created on a remote server. IMPORTANT: this list will be ignored by Butler in Interactive mode.
  - # IMPORTANT: first line after each '-' should be empty. 
    login: sm
    sshPubKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCid4Hus7s6QJK7sV1rf7h+4wItz9IevSQP6tzMDhDRJl+HuhCsUbRKS0//oVP++1YRdt0hPTWseJV6WWEVxLQvsIZ4dlFsokJlWsHZqQP3PTXKTWb66v+DYWQOQDVAP0OKymEtCvyVmpW5jSXfPJ0dbPNeXFSN1fwzL+/DOMKfTlGp2SertGKYx7J7bLgY2JlPMXHLIyclcB3VyO7pqyj1NPG2bNjV49eCmbVFGDnM3AYKQFO2Z0iDB6iGsBnGD4RvuUFgBQkLcYVvsp6bL6Syfc3xhogPqnESFLnaPQYBrHww03cZoulWYGzeCYbX1RLkMg7BAQQddXaWS2Q90GNF6xhxskFw3EVMO667jo+T2kYNop/tW2cK9ELffehI+W2/ticGlQOxDo/piHmFyTNYZW+zuXa2orrHO9OZbN2fLiRthKwhDWll91wwkJVLCGw/2HQR3om+noIcjLkqDmIMql1us/hcGh4/yX1WZwnugdMApmfG1p+SW6vsN21mhZ8= m.chingis@gmail.com"
    groups: "sudo,kvm"

# User to be created on the remote host and configured for you to run Butler
myUserLogin: sm

# Software to be installed on the remote server
software:
  list: path-to-list
...
# the above denotes the end of the document. However, there may be more documents
# in the same file. parse_yaml just ignores these markers that are needed to be 
# YAML compliant.