alias compot="sudo docker-compose down && sudo docker-compose up -d"
alias dclogs="sudo docker-compose logs -f --tail=300"
alias gclone="sudo git clone"
alias gpull="sudo git pull"
alias dcup="sudo docker-compose up -d"
alias dcdown="sudo docker-compose down"
alias dcs="sudo docker ps -a"
alias dcexec="sudo docker-compose exec"
#alias ll="ls -la"
alias gpull="git pull"
alias gpush="git push"
alias gadd="git add -A"
